version: '2'

services:
  db:
    image: couchbase
    container_name: db
    ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 8094:8094
    - 11210:11210
    - 11211:11211
    networks:
    - dockernet2


  app:
    build: .
    image: rbougrin/initdata:1
    links:
    - "db:couchbase"
    environment:
    - DB_URI=couchbase:8091

networks:
  dockernet2:
    external: true